### ISSUE TITLE
Health System

### ISSUE THREAD

**Issue by jpeter17** [stewartjustinl/Project2Game#16]
TODO: Implement Player Health System

**Comment by bsumser** [comment]
Added simple health system to enemy prefabs (6263417d2bd58fe41436e62ff468c9f8cb23697b). HitDetectorEnemy gives enemies an integer health value of 3, and each projectile hit decreases it by 1. In the Update() routine, when health == 0, the enemy gameobject is destroyed.

**Comment by jpeter17** [comment]
Added Player Health System and Food Pickups (fe5cca3)

Player starts with Health of 3.
Loses Health on Projectile collision, games health on food collision
