### ISSUE TITLE
Camera Controller

### ISSUE THREAD

**Issue by stewartjustinl** [stewartjustinl/Project2Game#6]
I know we originally decided to try to simply attach the main camera to the player and have it move that way but when i did it it looked awefull. i am working on a camera that will allow us to move with the player as well as will readjust itself so we don't clip through walls. features will be the following.

Moves with player. 
mouse will control your ability to look around the scene during play. 
readjusts for object collision so your not stuck behind a wall or inside of it. 
possibly more as i design. this should be ready hopefully by end of day Nov 12 2020 .

**Comment by stewartjustinl** [comment]
This is going to be accomplished with the help of the cinimachine package

**Comment by jpeter17** [comment]
Top-Down Camera has been finished, WASD for movement, player looks/shoots at mouse
