### ISSUE TITLE
Player Controller

### ISSUE THREAD

**Issue by stewartjustinl** [stewartjustinl/Project2Game#7]
I am designing a player controller to allow smooth movement of the player around the map. the movement will allow for either w, a,s,d, or arrows as the player movement but will not be part of the remappable keys at this time since unity uses axis controllers for this.

**Comment by jpeter17** [comment]
Player movement has been implemented 

TODO: Update Player Asset

**Comment by jpeter17** [comment]
Player Asset has been updated
